## <center>Trabalhando com ArrayNumpy - Index</center>

In [1]:
import numpy as np

Trazer os arrays para cá

In [2]:
array1 = np.array([10, 21, 31, 47, 121, 56, 98])

In [3]:
array1

array([ 10,  21,  31,  47, 121,  56,  98])

In [4]:
type(array1)

numpy.ndarray

In [5]:
## Buscando um elemento específico do array
array1[4]

121

In [6]:
## Extraindo um intervalo do array através dos indeces
array1[4:]

array([121,  56,  98])

In [7]:
# Uma outra forma de extrair valores por indeces
array1[3:6+1]

array([ 47, 121,  56,  98])

In [8]:
## Criando uma lista de indices para leitura nas posições do arrays
indices = [1, 3, 5, 6]
array1[indices]

array([21, 47, 56, 98])

In [9]:
# Criando uma mascara booleano para elementos pares, poderia ser somente para impares também.
    ## Muito usada também em Preparação para Ciencia de dados
mascara = (array1 % 2 == 0)
mascara
    ## A mascara não retornará os valores, mas sim 'True' ou 'False'

array([ True, False, False, False, False,  True,  True])

In [10]:
## Mas também posso ter os valores da operação da mascara
array1[mascara]

array([10, 56, 98])

In [11]:
## Modificando valores dos indices do array
array1[1] = 32

In [12]:
contador = (array1 % 2 == 0)
array1[contador]

array([10, 32, 56, 98])

In [13]:
## Tentando inserir no array tipo diferente de dados
try:
    array1[0] = 'Novo tipo'
except:
    print('Tipo de dados incorrespondente')

Tipo de dados incorrespondente


### Funções NumPy

### Matrizes NumPy

In [14]:
arrayMatrizes = np.array([[1, 11], [12, 23]])
arrayMatrizes

array([[ 1, 11],
       [12, 23]])

In [15]:
arrayMatrizes.shape

(2, 2)

In [16]:
arrayMatrizes2 = np.zeros((3,3))
arrayMatrizes2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arrayMatrizes3 = np.identity(4)
arrayMatrizes3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Manipulando Arquivos com NumPy

### Análise Estátistica com NumPy

O desvio padrão é uma medida estatística de dispensão que indica o quanto os valores de um conjunto de dados se afastam da média. Ele é calculado como a raiz quadrada da variância, que é a média dos quadrados das diferenças entre cada valor e a média.</br> O desvio padrão é uma medida útil porque permite avaliar a variabilidade. Por outro lado, se os valores estiverem muito distantes da média, o desvio padrão será alto, indicando que os dados tem alta variabilidade.</br> O desvio padrão é amplamente utilizado em Análise e Ciência de dados, para avaliar a consistência dos dados e comparar conjuntos de dados diferentes. É importante notar que o desvio padrão pode ser influência por valores extremos (outliers) e pode ser afetado por diferentes distribuições de dados.

In [18]:
teste = np.array([15, 23, 63 ,94,75])

In [19]:
np.mean(teste)

54.0

In [20]:
np.std(teste)

30.34468652004828

Variância é uma medida estatística que quantifica a dispersão dos valores em um conjunto de dados em relação à média. Ela é calculada como a média dos quadrados das diferenças entre cada valor e a média.

Tanto a variância quanto o desvio padrão são medidas úteis de dispersão e podem ser usados em conjunto para descrever a distribuição de um conjunto de dados. </br>A variância é uma medida quadrática e pode ser útil para calcular outras estatísticas, como o desvio padrão. No entanto, como a variância é uma medida quadrática, seus valores são geralmente maiores do que os valores dos próprios dados, o que pode dificultar a interpretação. O desvio padrão é a raiz quadrada da variância e fornece uma medida de dispersão que tem a mesma unidade de medida que os próprios dados, facilitando a interpretação e a comparação com outros valores.</br>Em geral, o desvio padrão é mais comumente usado do que a variância, principalmente porque é mais fácil de interpretar. No entanto, a escolha entre o uso da variância ou do desvio padrão depende do contexto e do objetivo da análise. Em alguns casos, a variância pode ser uma medida  mais  apropriada,  como  quando  se  pretende  calcular  outras  estatísticas,  como  a covariância ou o coeficiente de correlação. Em outros casos, o desvio padrão pode ser uma medida mais apropriada, como quando se pretende avaliar a consistência dos dados em relação à média e comparar diferentes conjuntos de dados.